
name: Build shared libraries

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    name: Build shared libraries + APK
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25
          add-to-path: false

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build shared libraries + APK
        shell: bash
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload sample app
        uses: actions/upload-artifact@v3
        if: ${{ !github.head_ref }}
        with:
          name: sample-app
          path: |
            app/build/outputs/apk/debug/app-debug.apk

      - name: Upload shared libraries
        uses: actions/upload-artifact@v3
        if: ${{ !github.head_ref }}
        with:
          name: shared-libraries
          path: |
            output/aarch64-linux-android21/libts.so
            output/armv7a-linux-android21/libts.so
            output/x86_64-linux-android21/libts.so
            output/i686-linux-android21/libts.so